---
- name: Cisco show version play
  hosts: Ciscooooo
  tasks:
  
    - name: Show version testing
      cisco.ios.ios_command:
        commands: show version

- name: Print output of /tmp/test-cisco.txt
  hosts: localhost
  tasks:

    - name: Capture /tmp/test-cisco.txt
      shell: cat /tmp/test-cisco.txt
      register: cisco_output
      
    - name: Print the var
      debug:
        var: cisco_output.stdout
