---
- name: Make a simple test playbook
  hosts: localhost
  tasks:
  
    - name: Show version testing
      cisco.ios.ios_command:
        commands: show version

    - name: Capture /tmp/test-cisco.txt
      shell: cat /tmp/test-cisco.txt
      register: cisco-output
      
    - name: Print the var
      debug:
        var: cisco-output.stdout
